version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: starbase_app
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=dev
      - PYTHONPATH=/home/starbase:/home/starbase/src
      - PYTHONNOUSERSITE=1  # Prevent loading packages from user site
    volumes:
      - .:/home/starbase:rw
      - ./src/database/db:/home/starbase/src/database/db:rw
    restart: always
    command: ["./start-script.sh"]
  unit-tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: starbase_tests
    environment:
      - PYTHONPATH=/home/starbase:/home/starbase/src
    volumes:
      - .:/home/starbase
      - ./src/database/db:/home/starbase/src/database/db
    command: ["pytest", "-v"]