version: "3.7"
services:
  dashboard:
    build:
      context: ./
    container_name: "starbase"
    hostname: "starbase"
    restart: always
    networks:
      - default
    ports:
      - 7000:80
