services:
  redis:
    image: redis:7-alpine
    container_name: starbase_redis
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: starbase:latest
    container_name: starbase_app
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/home/starbase:/home/starbase/src
      - PYTHONNOUSERSITE=1  # Prevent loading packages from user site
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      # Mount only specific directories to avoid overwriting conda installation
      - ./src:/home/starbase/src:rw
      - ./environment.yaml:/home/starbase/environment.yaml:ro
      - ./start-script.sh:/home/starbase/start-script.sh:ro
      - ./app.py:/home/starbase/app.py:ro
      - ./src/database/db:/home/starbase/src/database/db:rw
    depends_on:
      redis:
        condition: service_healthy
    restart: always

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: starbase:latest
    container_name: starbase_celery_worker
    environment:
      - PYTHONPATH=/home/starbase:/home/starbase/src
      - PYTHONNOUSERSITE=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./src:/home/starbase/src:rw
      - ./src/database/db:/home/starbase/src/database/db:rw
      - ./manage_celery.py:/home/starbase/manage_celery.py:ro
    depends_on:
      redis:
        condition: service_healthy
    entrypoint: ["python"]
    command: ["manage_celery.py", "worker"]
    restart: always

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    image: starbase:latest
    container_name: starbase_celery_beat
    environment:
      - PYTHONPATH=/home/starbase:/home/starbase/src
      - PYTHONNOUSERSITE=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./src:/home/starbase/src:rw
      - ./src/database/db:/home/starbase/src/database/db:rw
      - ./manage_celery.py:/home/starbase/manage_celery.py:ro
    depends_on:
      redis:
        condition: service_healthy
    entrypoint: ["python"]
    command: ["manage_celery.py", "beat"]
    restart: always
  
  unit-tests:
    image: starbase:latest
    container_name: starbase_tests
    depends_on:
      - app
    environment:
      - PYTHONPATH=/home/starbase:/home/starbase/src
    volumes:
      # Mount only specific directories to avoid overwriting conda installation
      - ./src:/home/starbase/src:rw
      - ./environment.yaml:/home/starbase/environment.yaml:ro
      - ./start-script.sh:/home/starbase/start-script.sh:ro
      - ./app.py:/home/starbase/app.py:ro
      - ./src/database/db:/home/starbase/src/database/db:rw
    entrypoint: ["pytest"]
    command: ["-v"]
    profiles:
      - testing