services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: starbase:latest
    container_name: starbase_app
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/home/starbase:/home/starbase/src
      - PYTHONNOUSERSITE=1  # Prevent loading packages from user site
    volumes:
      # Mount only specific directories to avoid overwriting conda installation
      - ./src:/home/starbase/src:rw
      - ./environment.yaml:/home/starbase/environment.yaml:ro
      - ./start-script.sh:/home/starbase/start-script.sh:ro
      - ./app.py:/home/starbase/app.py:ro
      - ./src/database/db:/home/starbase/src/database/db:rw
    restart: always
  
  unit-tests:
    image: starbase:latest
    container_name: starbase_tests
    depends_on:
      - app
    environment:
      - PYTHONPATH=/home/starbase:/home/starbase/src
    volumes:
      # Mount only specific directories to avoid overwriting conda installation
      - ./src:/home/starbase/src:rw
      - ./environment.yaml:/home/starbase/environment.yaml:ro
      - ./start-script.sh:/home/starbase/start-script.sh:ro
      - ./app.py:/home/starbase/app.py:ro
      - ./src/database/db:/home/starbase/src/database/db:rw
    entrypoint: ["pytest"]
    command: ["-v"]
    profiles:
      - testing