version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: starbase_app
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=dev
    volumes:
      - .:/home/starbase
      - ./src/database/db:/home/starbase/src/database/db
    restart: always
    command: ["bash", "./start-script.sh"]
  unit-tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: starbase_app
    environment:
      - PYTHONPATH=/home/starbase:/home/starbase/src
    volumes:
      - .:/home/starbase
      - ./src/database/db:/home/starbase/src/database/db
    command: ["pytest", "-v"]