"""Baseline - current database state

Revision ID: b29b0a6f346b
Revises:
Create Date: 2025-08-29 12:02:22.266524

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b29b0a6f346b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite requires batch mode (table recreate) for column/constraint
    # changes -- alter_column/create_foreign_key/drop_constraint/
    # create_unique_constraint can't run as bare ALTER TABLE statements.
    # sqlite_sequence is SQLite-internal (tracks AUTOINCREMENT); it can't be
    # dropped and doesn't need to be -- see downgrade().
    with op.batch_alter_table("accessions") as batch_op:
        batch_op.alter_column(
            "ship_name",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "accession_tag",
            existing_type=sa.NUMERIC(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "version_tag",
            existing_type=sa.INTEGER(),
            type_=sa.String(),
            nullable=True,
            existing_server_default=sa.text("1"),
        )
        batch_op.drop_index(op.f("idx_accessions_id"))
        batch_op.drop_index(op.f("idx_accessions_tag"))
        batch_op.create_unique_constraint(None, ["accession_tag"])

    with op.batch_alter_table("captains") as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )
        batch_op.alter_column(
            "captainID",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "sequence",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "reviewed",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.create_unique_constraint(None, ["captainID"])
        batch_op.create_foreign_key(None, "accessions", ["ship_id"], ["id"])
        batch_op.drop_column("evidence")

    with op.batch_alter_table("family_names") as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.INTEGER(),
            nullable=False,
            autoincrement=True,
        )
        batch_op.drop_index(op.f("idx_family_names_family"))
        batch_op.drop_index(op.f("idx_family_names_reference"))

    with op.batch_alter_table("genomes") as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )
        batch_op.drop_index(op.f("idx_genomes_taxonomy_id"))
        batch_op.create_foreign_key(None, "taxonomy", ["taxonomy_id"], ["id"])
        batch_op.drop_column("assembly_accession")

    with op.batch_alter_table("gff") as batch_op:
        batch_op.add_column(sa.Column("contigID", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("accession", sa.String(), nullable=True))
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )
        batch_op.alter_column(
            "phase",
            existing_type=sa.VARCHAR(),
            type_=sa.Integer(),
            existing_nullable=True,
        )
        batch_op.drop_index(op.f("idx_gff_accession_id"))
        batch_op.drop_index(op.f("idx_gff_ship_id"))
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "accessions", ["ship_id"], ["id"])
        batch_op.drop_column("accession_id")

    with op.batch_alter_table("haplotype_names") as batch_op:
        batch_op.alter_column(
            "haplotype_name",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "previous_haplotype_name",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.create_foreign_key(None, "family_names", ["ship_family_id"], ["id"])
        batch_op.create_foreign_key(None, "navis_names", ["navis_id"], ["id"])

    with op.batch_alter_table("joined_ships") as batch_op:
        batch_op.add_column(sa.Column("genus", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("species", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("strain", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("contigID", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("captainID", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("elementBegin", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("elementEnd", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("size", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("strand", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("boundaryType", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("emptySiteID", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("emptyContig", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("emptyBegin", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("emptyEnd", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("emptySeq", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("upDR", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("downDR", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("DRedit", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("upTIR", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("downTIR", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("TIRedit", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("nestedInside", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("containNested", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("dr", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("tir", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("navis_name", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("haplotype_name", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("target", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("spok", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("ars", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("other", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("hgt", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("taxid", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("ome", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("orphan", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("captainID_new", sa.Integer(), nullable=True))
        batch_op.alter_column(
            "id",
            existing_type=sa.INTEGER(),
            nullable=False,
            autoincrement=True,
        )
        batch_op.alter_column(
            "starshipID",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            nullable=True,
        )
        batch_op.alter_column(
            "evidence",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "source",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "curated_status",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "genome_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.drop_index(op.f("idx_joined_ships_curated"))
        batch_op.drop_index(op.f("idx_joined_ships_final_captain"))
        batch_op.drop_index(op.f("idx_joined_ships_final_family"))
        batch_op.drop_index(op.f("idx_joined_ships_final_genome"))
        batch_op.drop_index(op.f("idx_joined_ships_final_haplotype"))
        batch_op.drop_index(op.f("idx_joined_ships_final_navis"))
        batch_op.drop_index(op.f("idx_joined_ships_final_ship"))
        batch_op.drop_index(op.f("idx_joined_ships_final_starshipid"))
        batch_op.drop_index(op.f("idx_joined_ships_final_taxonomy"))
        batch_op.drop_index(op.f("idx_joined_ships_genome_id"))
        batch_op.drop_index(op.f("idx_joined_ships_ship_family_id"))
        batch_op.drop_index(op.f("idx_joined_ships_ship_haplotype_id"))
        batch_op.drop_index(op.f("idx_joined_ships_ship_id"))
        batch_op.drop_index(op.f("idx_joined_ships_ship_navis_id"))
        batch_op.drop_index(op.f("idx_joined_ships_tax_id"))
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "accessions", ["ship_id"], ["id"])
        batch_op.drop_column("ship_navis_id")
        batch_op.drop_column("ship_haplotype_id")
        batch_op.drop_column("updated_at")
        batch_op.drop_column("tax_id")
        batch_op.drop_column("captain_id")
        batch_op.drop_column("created_at")

    with op.batch_alter_table("navis_names") as batch_op:
        batch_op.alter_column(
            "navis_name",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "previous_navis_name",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "ship_family_id",
            existing_type=sa.TEXT(),
            type_=sa.Integer(),
            existing_nullable=True,
        )
        batch_op.create_foreign_key(None, "family_names", ["ship_family_id"], ["id"])

    with op.batch_alter_table("papers") as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )
        batch_op.alter_column(
            "Key",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "ItemType",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "Author",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "Title",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "PublicationTitle",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "DOI",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "Url",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "AbstractNote",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "Date",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "starshipMentioned",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "typePaper",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )

    with op.batch_alter_table("ships") as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )
        batch_op.alter_column(
            "sequence",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "md5",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.drop_index(op.f("idx_ships_accession_id"))
        batch_op.drop_column("sequence_length")
        batch_op.drop_column("header")

    with op.batch_alter_table("starship_features") as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.INTEGER(),
            nullable=False,
            autoincrement=True,
        )
        batch_op.drop_index(op.f("idx_starship_features_accession_id"))
        batch_op.drop_index(op.f("idx_starship_features_ship_id"))
        batch_op.drop_index(op.f("idx_starship_features_starshipID"))
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "captains", ["captain_id"], ["id"])
        batch_op.create_foreign_key(None, "accessions", ["ship_id"], ["id"])
        batch_op.drop_column("accession_id")
        batch_op.drop_column("target")
        batch_op.drop_column("other")
        batch_op.drop_column("spok")
        batch_op.drop_column("tir")
        batch_op.drop_column("hgt")
        batch_op.drop_column("dr")
        batch_op.drop_column("ars")

    with op.batch_alter_table("taxonomy") as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )
        batch_op.drop_index(op.f("idx_taxonomy_name"))
        batch_op.drop_index(op.f("idx_taxonomy_species"))
        batch_op.drop_index(op.f("idx_taxonomy_taxid"))
        batch_op.drop_column("strain")
        batch_op.drop_column("species_group")
        batch_op.drop_column("subgenus")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taxonomy") as batch_op:
        batch_op.add_column(sa.Column("subgenus", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("species_group", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("strain", sa.VARCHAR(), nullable=True))
        batch_op.create_index(op.f("idx_taxonomy_taxid"), ["taxID"], unique=False)
        batch_op.create_index(op.f("idx_taxonomy_species"), ["species"], unique=False)
        batch_op.create_index(op.f("idx_taxonomy_name"), ["name"], unique=False)
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    with op.batch_alter_table("starship_features") as batch_op:
        batch_op.add_column(sa.Column("ars", sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column("dr", sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column("hgt", sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column("tir", sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column("spok", sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column("other", sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column("target", sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column("accession_id", sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "accessions", ["accession_id"], ["id"])
        batch_op.create_foreign_key(None, "ships", ["ship_id"], ["id"])
        batch_op.create_index(
            op.f("idx_starship_features_starshipID"), ["starshipID"], unique=False
        )
        batch_op.create_index(
            op.f("idx_starship_features_ship_id"), ["ship_id"], unique=False
        )
        batch_op.create_index(
            op.f("idx_starship_features_accession_id"),
            ["accession_id"],
            unique=False,
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.INTEGER(),
            nullable=True,
            autoincrement=True,
        )

    with op.batch_alter_table("ships") as batch_op:
        batch_op.add_column(sa.Column("header", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("sequence_length", sa.INTEGER(), nullable=True))
        batch_op.create_index(
            op.f("idx_ships_accession_id"), ["accession_id"], unique=False
        )
        batch_op.alter_column(
            "md5",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "sequence",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    with op.batch_alter_table("papers") as batch_op:
        batch_op.alter_column(
            "typePaper",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "starshipMentioned",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "Date",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "AbstractNote",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "Url",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "DOI",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "PublicationTitle",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "Title",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "Author",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "ItemType",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "Key",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    with op.batch_alter_table("navis_names") as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.alter_column(
            "ship_family_id",
            existing_type=sa.Integer(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "previous_navis_name",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "navis_name",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )

    with op.batch_alter_table("joined_ships") as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DATETIME(),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=True,
            )
        )
        batch_op.add_column(sa.Column("captain_id", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("tax_id", sa.INTEGER(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DATETIME(),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column("ship_haplotype_id", sa.INTEGER(), nullable=True)
        )
        batch_op.add_column(sa.Column("ship_navis_id", sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "navis_names", ["ship_navis_id"], ["id"])
        batch_op.create_foreign_key(None, "captains", ["captain_id"], ["id"])
        batch_op.create_foreign_key(None, "taxonomy", ["tax_id"], ["id"])
        batch_op.create_foreign_key(
            None, "haplotype_names", ["ship_haplotype_id"], ["id"]
        )
        batch_op.create_foreign_key(None, "genomes", ["genome_id"], ["id"])
        batch_op.create_index(op.f("idx_joined_ships_tax_id"), ["tax_id"], unique=False)
        batch_op.create_index(
            op.f("idx_joined_ships_ship_navis_id"), ["ship_navis_id"], unique=False
        )
        batch_op.create_index(
            op.f("idx_joined_ships_ship_id"), ["ship_id"], unique=False
        )
        batch_op.create_index(
            op.f("idx_joined_ships_ship_haplotype_id"),
            ["ship_haplotype_id"],
            unique=False,
        )
        batch_op.create_index(
            op.f("idx_joined_ships_ship_family_id"),
            ["ship_family_id"],
            unique=False,
        )
        batch_op.create_index(
            op.f("idx_joined_ships_genome_id"), ["genome_id"], unique=False
        )
        batch_op.create_index(
            op.f("idx_joined_ships_final_taxonomy"), ["tax_id"], unique=False
        )
        batch_op.create_index(
            op.f("idx_joined_ships_final_starshipid"),
            ["starshipID"],
            unique=False,
        )
        batch_op.create_index(
            op.f("idx_joined_ships_final_ship"), ["ship_id"], unique=False
        )
        batch_op.create_index(
            op.f("idx_joined_ships_final_navis"), ["ship_navis_id"], unique=False
        )
        batch_op.create_index(
            op.f("idx_joined_ships_final_haplotype"),
            ["ship_haplotype_id"],
            unique=False,
        )
        batch_op.create_index(
            op.f("idx_joined_ships_final_genome"), ["genome_id"], unique=False
        )
        batch_op.create_index(
            op.f("idx_joined_ships_final_family"),
            ["ship_family_id"],
            unique=False,
        )
        batch_op.create_index(
            op.f("idx_joined_ships_final_captain"), ["captain_id"], unique=False
        )
        batch_op.create_index(
            op.f("idx_joined_ships_curated"), ["curated_status"], unique=False
        )
        batch_op.alter_column(
            "genome_id",
            existing_type=sa.String(),
            type_=sa.INTEGER(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "curated_status",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "source",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "evidence",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "starshipID",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            nullable=False,
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.INTEGER(),
            nullable=True,
            autoincrement=True,
        )
        batch_op.drop_column("captainID_new")
        batch_op.drop_column("orphan")
        batch_op.drop_column("ome")
        batch_op.drop_column("taxid")
        batch_op.drop_column("hgt")
        batch_op.drop_column("other")
        batch_op.drop_column("ars")
        batch_op.drop_column("spok")
        batch_op.drop_column("target")
        batch_op.drop_column("haplotype_name")
        batch_op.drop_column("navis_name")
        batch_op.drop_column("tir")
        batch_op.drop_column("dr")
        batch_op.drop_column("containNested")
        batch_op.drop_column("nestedInside")
        batch_op.drop_column("TIRedit")
        batch_op.drop_column("downTIR")
        batch_op.drop_column("upTIR")
        batch_op.drop_column("DRedit")
        batch_op.drop_column("downDR")
        batch_op.drop_column("upDR")
        batch_op.drop_column("emptySeq")
        batch_op.drop_column("emptyEnd")
        batch_op.drop_column("emptyBegin")
        batch_op.drop_column("emptyContig")
        batch_op.drop_column("emptySiteID")
        batch_op.drop_column("boundaryType")
        batch_op.drop_column("strand")
        batch_op.drop_column("size")
        batch_op.drop_column("elementEnd")
        batch_op.drop_column("elementBegin")
        batch_op.drop_column("captainID")
        batch_op.drop_column("contigID")
        batch_op.drop_column("strain")
        batch_op.drop_column("species")
        batch_op.drop_column("genus")

    with op.batch_alter_table("haplotype_names") as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.alter_column(
            "previous_haplotype_name",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "haplotype_name",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )

    with op.batch_alter_table("gff") as batch_op:
        batch_op.add_column(sa.Column("accession_id", sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "ships", ["ship_id"], ["id"])
        batch_op.create_foreign_key(None, "accessions", ["accession_id"], ["id"])
        batch_op.create_index(op.f("idx_gff_ship_id"), ["ship_id"], unique=False)
        batch_op.create_index(
            op.f("idx_gff_accession_id"), ["accession_id"], unique=False
        )
        batch_op.alter_column(
            "phase",
            existing_type=sa.Integer(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )
        batch_op.drop_column("accession")
        batch_op.drop_column("contigID")

    with op.batch_alter_table("genomes") as batch_op:
        batch_op.add_column(sa.Column("assembly_accession", sa.TEXT(), nullable=True))
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_index(
            op.f("idx_genomes_taxonomy_id"), ["taxonomy_id"], unique=False
        )
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    with op.batch_alter_table("family_names") as batch_op:
        batch_op.create_index(
            op.f("idx_family_names_reference"),
            ["type_element_reference"],
            unique=False,
        )
        batch_op.create_index(
            op.f("idx_family_names_family"), ["familyName"], unique=False
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.INTEGER(),
            nullable=True,
            autoincrement=True,
        )

    with op.batch_alter_table("captains") as batch_op:
        batch_op.add_column(sa.Column("evidence", sa.TEXT(), nullable=True))
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="unique")
        batch_op.alter_column(
            "reviewed",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "sequence",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "captainID",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    with op.batch_alter_table("accessions") as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.create_index(
            op.f("idx_accessions_tag"), ["accession_tag"], unique=False
        )
        batch_op.create_index(op.f("idx_accessions_id"), ["id"], unique=False)
        batch_op.alter_column(
            "version_tag",
            existing_type=sa.String(),
            type_=sa.INTEGER(),
            nullable=False,
            existing_server_default=sa.text("1"),
        )
        batch_op.alter_column(
            "accession_tag",
            existing_type=sa.String(),
            type_=sa.NUMERIC(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "ship_name",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
    # sqlite_sequence intentionally not recreated here -- see upgrade().
    # ### end Alembic commands ###
