apiVersion: v1
kind: PersistentVolume
metadata:
  name: starbase-db-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/starbase-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: starbase-db-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 