apiVersion: v1
kind: PersistentVolume
metadata:
  name: starbase-test-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/starbase-test-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: starbase-test-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: starbase-temp-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/starbase-temp-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: starbase-temp-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
